cd diaparser/

mkdir models

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_English-EWT/en_ewt-ud-train.conllu --dev ../UD_data/UD_English-EWT/en_ewt-ud-dev.conllu --test ../UD_data/UD_English-EWT/en_ewt-ud-test.conllu  -b -d 0 -p models/en_ewt/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_English-EWT/en_ewt-ud-train.conllu --dev ../UD_data/UD_English-EWT/en_ewt-ud-dev.conllu --test ../UD_data/UD_English-EWT/en_ewt-ud-test.conllu  -b -d 0 -p models/en_ewt/mbert_2  -f bert  --bert bert-base-multilingual-cased  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_English-EWT/en_ewt-ud-train.conllu --dev ../UD_data/UD_English-EWT/en_ewt-ud-dev.conllu --test ../UD_data/UD_English-EWT/en_ewt-ud-test.conllu  -b -d 0 -p models/en_ewt/mbert_3  -f bert  --bert bert-base-multilingual-cased  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_English-EWT/en_ewt-ud-train.conllu --dev ../UD_data/UD_English-EWT/en_ewt-ud-dev.conllu --test ../UD_data/UD_English-EWT/en_ewt-ud-test.conllu  -b -d 0 -p models/en_ewt/xlmr_1  -f bert  --bert xlm-roberta-base  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_English-EWT/en_ewt-ud-train.conllu --dev ../UD_data/UD_English-EWT/en_ewt-ud-dev.conllu --test ../UD_data/UD_English-EWT/en_ewt-ud-test.conllu  -b -d 0 -p models/en_ewt/xlmr_2  -f bert  --bert xlm-roberta-base  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_English-EWT/en_ewt-ud-train.conllu --dev ../UD_data/UD_English-EWT/en_ewt-ud-dev.conllu --test ../UD_data/UD_English-EWT/en_ewt-ud-test.conllu  -b -d 0 -p models/en_ewt/xlmr_3  -f bert  --bert xlm-roberta-base  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Spanish-AnCora/es_ancora-ud-train.conllu --dev ../UD_data/UD_Spanish-AnCora/es_ancora-ud-dev.conllu --test ../UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu  -b -d 0 -p models/es_ancora/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Spanish-AnCora/es_ancora-ud-train.conllu --dev ../UD_data/UD_Spanish-AnCora/es_ancora-ud-dev.conllu --test ../UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu  -b -d 0 -p models/es_ancora/mbert_2  -f bert  --bert bert-base-multilingual-cased  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Spanish-AnCora/es_ancora-ud-train.conllu --dev ../UD_data/UD_Spanish-AnCora/es_ancora-ud-dev.conllu --test ../UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu  -b -d 0 -p models/es_ancora/mbert_3  -f bert  --bert bert-base-multilingual-cased  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Spanish-AnCora/es_ancora-ud-train.conllu --dev ../UD_data/UD_Spanish-AnCora/es_ancora-ud-dev.conllu --test ../UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu  -b -d 0 -p models/es_ancora/xlmr_1  -f bert  --bert xlm-roberta-base  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Spanish-AnCora/es_ancora-ud-train.conllu --dev ../UD_data/UD_Spanish-AnCora/es_ancora-ud-dev.conllu --test ../UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu  -b -d 0 -p models/es_ancora/xlmr_2  -f bert  --bert xlm-roberta-base  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Spanish-AnCora/es_ancora-ud-train.conllu --dev ../UD_data/UD_Spanish-AnCora/es_ancora-ud-dev.conllu --test ../UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu  -b -d 0 -p models/es_ancora/xlmr_3  -f bert  --bert xlm-roberta-base  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Croatian-SET/hr_set-ud-train.conllu --dev ../UD_data/UD_Croatian-SET/hr_set-ud-dev.conllu --test ../UD_data/UD_Croatian-SET/hr_set-ud-test.conllu  -b -d 0 -p models/hr_set/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Croatian-SET/hr_set-ud-train.conllu --dev ../UD_data/UD_Croatian-SET/hr_set-ud-dev.conllu --test ../UD_data/UD_Croatian-SET/hr_set-ud-test.conllu  -b -d 0 -p models/hr_set/mbert_2  -f bert  --bert bert-base-multilingual-cased  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Croatian-SET/hr_set-ud-train.conllu --dev ../UD_data/UD_Croatian-SET/hr_set-ud-dev.conllu --test ../UD_data/UD_Croatian-SET/hr_set-ud-test.conllu  -b -d 0 -p models/hr_set/mbert_3  -f bert  --bert bert-base-multilingual-cased  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Croatian-SET/hr_set-ud-train.conllu --dev ../UD_data/UD_Croatian-SET/hr_set-ud-dev.conllu --test ../UD_data/UD_Croatian-SET/hr_set-ud-test.conllu  -b -d 0 -p models/hr_set/xlmr_1  -f bert  --bert xlm-roberta-base  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Croatian-SET/hr_set-ud-train.conllu --dev ../UD_data/UD_Croatian-SET/hr_set-ud-dev.conllu --test ../UD_data/UD_Croatian-SET/hr_set-ud-test.conllu  -b -d 0 -p models/hr_set/xlmr_2  -f bert  --bert xlm-roberta-base  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Croatian-SET/hr_set-ud-train.conllu --dev ../UD_data/UD_Croatian-SET/hr_set-ud-dev.conllu --test ../UD_data/UD_Croatian-SET/hr_set-ud-test.conllu  -b -d 0 -p models/hr_set/xlmr_3  -f bert  --bert xlm-roberta-base  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-train.conllu --dev ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-dev.conllu --test ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-test.conllu  -b -d 0 -p models/pt_gsd/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-train.conllu --dev ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-dev.conllu --test ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-test.conllu  -b -d 0 -p models/pt_gsd/mbert_2  -f bert  --bert bert-base-multilingual-cased  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-train.conllu --dev ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-dev.conllu --test ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-test.conllu  -b -d 0 -p models/pt_gsd/mbert_3  -f bert  --bert bert-base-multilingual-cased  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-train.conllu --dev ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-dev.conllu --test ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-test.conllu  -b -d 0 -p models/pt_gsd/xlmr_1  -f bert  --bert xlm-roberta-base  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-train.conllu --dev ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-dev.conllu --test ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-test.conllu  -b -d 0 -p models/pt_gsd/xlmr_2  -f bert  --bert xlm-roberta-base  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-train.conllu --dev ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-dev.conllu --test ../UD_data/UD_Portuguese-GSD/pt_gsd-ud-test.conllu  -b -d 0 -p models/pt_gsd/xlmr_3  -f bert  --bert xlm-roberta-base  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Czech-PDT/cs_pdt-ud-train.conllu --dev ../UD_data/UD_Czech-PDT/cs_pdt-ud-dev.conllu --test ../UD_data/UD_Czech-PDT/cs_pdt-ud-test.conllu  -b -d 0 -p models/cs_pdt/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Czech-PDT/cs_pdt-ud-train.conllu --dev ../UD_data/UD_Czech-PDT/cs_pdt-ud-dev.conllu --test ../UD_data/UD_Czech-PDT/cs_pdt-ud-test.conllu  -b -d 0 -p models/cs_pdt/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Czech-PDT/cs_pdt-ud-train.conllu --dev ../UD_data/UD_Czech-PDT/cs_pdt-ud-dev.conllu --test ../UD_data/UD_Czech-PDT/cs_pdt-ud-test.conllu  -b -d 0 -p models/cs_pdt/mbert_1  -f bert  --bert bert-base-multilingual-cased  -s 3

python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Czech-PDT/cs_pdt-ud-train.conllu --dev ../UD_data/UD_Czech-PDT/cs_pdt-ud-dev.conllu --test ../UD_data/UD_Czech-PDT/cs_pdt-ud-test.conllu  -b -d 0 -p models/cs_pdt/xlmr_1  -f bert  --bert xlm-roberta-base  -s 1
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Czech-PDT/cs_pdt-ud-train.conllu --dev ../UD_data/UD_Czech-PDT/cs_pdt-ud-dev.conllu --test ../UD_data/UD_Czech-PDT/cs_pdt-ud-test.conllu  -b -d 0 -p models/cs_pdt/xlmr_1  -f bert  --bert xlm-roberta-base  -s 2
python -m diaparser.cmds.biaffine_dependency train --train ../UD_data/UD_Czech-PDT/cs_pdt-ud-train.conllu --dev ../UD_data/UD_Czech-PDT/cs_pdt-ud-dev.conllu --test ../UD_data/UD_Czech-PDT/cs_pdt-ud-test.conllu  -b -d 0 -p models/cs_pdt/xlmr_1  -f bert  --bert xlm-roberta-base  -s 3

cd ..